// Comprehensive element data with all 118 elements
const elementsData = [
    // Period 1
    { atomicNumber: 1, symbol: 'H', name: 'Hydrogen', atomicMass: 1.008, category: 'nonmetals', electronConfig: '1s¹', phase: 'Gas', discovered: 1766, position: { period: 1, group: 1 } },
    { atomicNumber: 2, symbol: 'He', name: 'Helium', atomicMass: 4.003, category: 'noble-gases', electronConfig: '1s²', phase: 'Gas', discovered: 1868, position: { period: 1, group: 18 } },
    
    // Period 2
    { atomicNumber: 3, symbol: 'Li', name: 'Lithium', atomicMass: 6.94, category: 'alkali-metals', electronConfig: '[He] 2s¹', phase: 'Solid', discovered: 1817, position: { period: 2, group: 1 } },
    { atomicNumber: 4, symbol: 'Be', name: 'Beryllium', atomicMass: 9.012, category: 'alkaline-earth-metals', electronConfig: '[He] 2s²', phase: 'Solid', discovered: 1798, position: { period: 2, group: 2 } },
    { atomicNumber: 5, symbol: 'B', name: 'Boron', atomicMass: 10.81, category: 'metalloids', electronConfig: '[He] 2s² 2p¹', phase: 'Solid', discovered: 1808, position: { period: 2, group: 13 } },
    { atomicNumber: 6, symbol: 'C', name: 'Carbon', atomicMass: 12.011, category: 'nonmetals', electronConfig: '[He] 2s² 2p²', phase: 'Solid', discovered: 'Ancient', position: { period: 2, group: 14 } },
    { atomicNumber: 7, symbol: 'N', name: 'Nitrogen', atomicMass: 14.007, category: 'nonmetals', electronConfig: '[He] 2s² 2p³', phase: 'Gas', discovered: 1772, position: { period: 2, group: 15 } },
    { atomicNumber: 8, symbol: 'O', name: 'Oxygen', atomicMass: 15.999, category: 'nonmetals', electronConfig: '[He] 2s² 2p⁴', phase: 'Gas', discovered: 1774, position: { period: 2, group: 16 } },
    { atomicNumber: 9, symbol: 'F', name: 'Fluorine', atomicMass: 18.998, category: 'halogens', electronConfig: '[He] 2s² 2p⁵', phase: 'Gas', discovered: 1886, position: { period: 2, group: 17 } },
    { atomicNumber: 10, symbol: 'Ne', name: 'Neon', atomicMass: 20.180, category: 'noble-gases', electronConfig: '[He] 2s² 2p⁶', phase: 'Gas', discovered: 1898, position: { period: 2, group: 18 } },
    
    // Period 3
    { atomicNumber: 11, symbol: 'Na', name: 'Sodium', atomicMass: 22.990, category: 'alkali-metals', electronConfig: '[Ne] 3s¹', phase: 'Solid', discovered: 1807, position: { period: 3, group: 1 } },
    { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium', atomicMass: 24.305, category: 'alkaline-earth-metals', electronConfig: '[Ne] 3s²', phase: 'Solid', discovered: 1808, position: { period: 3, group: 2 } },
    { atomicNumber: 13, symbol: 'Al', name: 'Aluminum', atomicMass: 26.982, category: 'post-transition-metals', electronConfig: '[Ne] 3s² 3p¹', phase: 'Solid', discovered: 1825, position: { period: 3, group: 13 } },
    { atomicNumber: 14, symbol: 'Si', name: 'Silicon', atomicMass: 28.085, category: 'metalloids', electronConfig: '[Ne] 3s² 3p²', phase: 'Solid', discovered: 1824, position: { period: 3, group: 14 } },
    { atomicNumber: 15, symbol: 'P', name: 'Phosphorus', atomicMass: 30.974, category: 'nonmetals', electronConfig: '[Ne] 3s² 3p³', phase: 'Solid', discovered: 1669, position: { period: 3, group: 15 } },
    { atomicNumber: 16, symbol: 'S', name: 'Sulfur', atomicMass: 32.06, category: 'nonmetals', electronConfig: '[Ne] 3s² 3p⁴', phase: 'Solid', discovered: 'Ancient', position: { period: 3, group: 16 } },
    { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine', atomicMass: 35.45, category: 'halogens', electronConfig: '[Ne] 3s² 3p⁵', phase: 'Gas', discovered: 1774, position: { period: 3, group: 17 } },
    { atomicNumber: 18, symbol: 'Ar', name: 'Argon', atomicMass: 39.948, category: 'noble-gases', electronConfig: '[Ne] 3s² 3p⁶', phase: 'Gas', discovered: 1894, position: { period: 3, group: 18 } },
    
    // Period 4
    { atomicNumber: 19, symbol: 'K', name: 'Potassium', atomicMass: 39.098, category: 'alkali-metals', electronConfig: '[Ar] 4s¹', phase: 'Solid', discovered: 1807, position: { period: 4, group: 1 } },
    { atomicNumber: 20, symbol: 'Ca', name: 'Calcium', atomicMass: 40.078, category: 'alkaline-earth-metals', electronConfig: '[Ar] 4s²', phase: 'Solid', discovered: 1808, position: { period: 4, group: 2 } },
    { atomicNumber: 21, symbol: 'Sc', name: 'Scandium', atomicMass: 44.956, category: 'transition-metals', electronConfig: '[Ar] 3d¹ 4s²', phase: 'Solid', discovered: 1879, position: { period: 4, group: 3 } },
    { atomicNumber: 22, symbol: 'Ti', name: 'Titanium', atomicMass: 47.867, category: 'transition-metals', electronConfig: '[Ar] 3d² 4s²', phase: 'Solid', discovered: 1791, position: { period: 4, group: 4 } },
    { atomicNumber: 23, symbol: 'V', name: 'Vanadium', atomicMass: 50.942, category: 'transition-metals', electronConfig: '[Ar] 3d³ 4s²', phase: 'Solid', discovered: 1801, position: { period: 4, group: 5 } },
    { atomicNumber: 24, symbol: 'Cr', name: 'Chromium', atomicMass: 51.996, category: 'transition-metals', electronConfig: '[Ar] 3d⁵ 4s¹', phase: 'Solid', discovered: 1797, position: { period: 4, group: 6 } },
    { atomicNumber: 25, symbol: 'Mn', name: 'Manganese', atomicMass: 54.938, category: 'transition-metals', electronConfig: '[Ar] 3d⁵ 4s²', phase: 'Solid', discovered: 1774, position: { period: 4, group: 7 } },
    { atomicNumber: 26, symbol: 'Fe', name: 'Iron', atomicMass: 55.845, category: 'transition-metals', electronConfig: '[Ar] 3d⁶ 4s²', phase: 'Solid', discovered: 'Ancient', position: { period: 4, group: 8 } },
    { atomicNumber: 27, symbol: 'Co', name: 'Cobalt', atomicMass: 58.933, category: 'transition-metals', electronConfig: '[Ar] 3d⁷ 4s²', phase: 'Solid', discovered: 1735, position: { period: 4, group: 9 } },
    { atomicNumber: 28, symbol: 'Ni', name: 'Nickel', atomicMass: 58.693, category: 'transition-metals', electronConfig: '[Ar] 3d⁸ 4s²', phase: 'Solid', discovered: 1751, position: { period: 4, group: 10 } },
    { atomicNumber: 29, symbol: 'Cu', name: 'Copper', atomicMass: 63.546, category: 'transition-metals', electronConfig: '[Ar] 3d¹⁰ 4s¹', phase: 'Solid', discovered: 'Ancient', position: { period: 4, group: 11 } },
    { atomicNumber: 30, symbol: 'Zn', name: 'Zinc', atomicMass: 65.38, category: 'transition-metals', electronConfig: '[Ar] 3d¹⁰ 4s²', phase: 'Solid', discovered: 1746, position: { period: 4, group: 12 } },
    { atomicNumber: 31, symbol: 'Ga', name: 'Gallium', atomicMass: 69.723, category: 'post-transition-metals', electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹', phase: 'Solid', discovered: 1875, position: { period: 4, group: 13 } },
    { atomicNumber: 32, symbol: 'Ge', name: 'Germanium', atomicMass: 72.630, category: 'metalloids', electronConfig: '[Ar] 3d¹⁰ 4s² 4p²', phase: 'Solid', discovered: 1886, position: { period: 4, group: 14 } },
    { atomicNumber: 33, symbol: 'As', name: 'Arsenic', atomicMass: 74.922, category: 'metalloids', electronConfig: '[Ar] 3d¹⁰ 4s² 4p³', phase: 'Solid', discovered: 'Ancient', position: { period: 4, group: 15 } },
    { atomicNumber: 34, symbol: 'Se', name: 'Selenium', atomicMass: 78.971, category: 'nonmetals', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴', phase: 'Solid', discovered: 1817, position: { period: 4, group: 16 } },
    { atomicNumber: 35, symbol: 'Br', name: 'Bromine', atomicMass: 79.904, category: 'halogens', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵', phase: 'Liquid', discovered: 1826, position: { period: 4, group: 17 } },
    { atomicNumber: 36, symbol: 'Kr', name: 'Krypton', atomicMass: 83.798, category: 'noble-gases', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶', phase: 'Gas', discovered: 1898, position: { period: 4, group: 18 } },
    
    // Period 5
    { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium', atomicMass: 85.468, category: 'alkali-metals', electronConfig: '[Kr] 5s¹', phase: 'Solid', discovered: 1861, position: { period: 5, group: 1 } },
    { atomicNumber: 38, symbol: 'Sr', name: 'Strontium', atomicMass: 87.62, category: 'alkaline-earth-metals', electronConfig: '[Kr] 5s²', phase: 'Solid', discovered: 1790, position: { period: 5, group: 2 } },
    { atomicNumber: 39, symbol: 'Y', name: 'Yttrium', atomicMass: 88.906, category: 'transition-metals', electronConfig: '[Kr] 4d¹ 5s²', phase: 'Solid', discovered: 1794, position: { period: 5, group: 3 } },
    { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium', atomicMass: 91.224, category: 'transition-metals', electronConfig: '[Kr] 4d² 5s²', phase: 'Solid', discovered: 1789, position: { period: 5, group: 4 } },
    { atomicNumber: 41, symbol: 'Nb', name: 'Niobium', atomicMass: 92.906, category: 'transition-metals', electronConfig: '[Kr] 4d⁴ 5s¹', phase: 'Solid', discovered: 1801, position: { period: 5, group: 5 } },
    { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum', atomicMass: 95.95, category: 'transition-metals', electronConfig: '[Kr] 4d⁵ 5s¹', phase: 'Solid', discovered: 1778, position: { period: 5, group: 6 } },
    { atomicNumber: 43, symbol: 'Tc', name: 'Technetium', atomicMass: 98, category: 'transition-metals', electronConfig: '[Kr] 4d⁵ 5s²', phase: 'Solid', discovered: 1937, position: { period: 5, group: 7 } },
    { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium', atomicMass: 101.07, category: 'transition-metals', electronConfig: '[Kr] 4d⁷ 5s¹', phase: 'Solid', discovered: 1844, position: { period: 5, group: 8 } },
    { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium', atomicMass: 102.91, category: 'transition-metals', electronConfig: '[Kr] 4d⁸ 5s¹', phase: 'Solid', discovered: 1803, position: { period: 5, group: 9 } },
    { atomicNumber: 46, symbol: 'Pd', name: 'Palladium', atomicMass: 106.42, category: 'transition-metals', electronConfig: '[Kr] 4d¹⁰', phase: 'Solid', discovered: 1803, position: { period: 5, group: 10 } },
    { atomicNumber: 47, symbol: 'Ag', name: 'Silver', atomicMass: 107.87, category: 'transition-metals', electronConfig: '[Kr] 4d¹⁰ 5s¹', phase: 'Solid', discovered: 'Ancient', position: { period: 5, group: 11 } },
    { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium', atomicMass: 112.41, category: 'transition-metals', electronConfig: '[Kr] 4d¹⁰ 5s²', phase: 'Solid', discovered: 1817, position: { period: 5, group: 12 } },
    { atomicNumber: 49, symbol: 'In', name: 'Indium', atomicMass: 114.82, category: 'post-transition-metals', electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹', phase: 'Solid', discovered: 1863, position: { period: 5, group: 13 } },
    { atomicNumber: 50, symbol: 'Sn', name: 'Tin', atomicMass: 118.71, category: 'post-transition-metals', electronConfig: '[Kr] 4d¹⁰ 5s² 5p²', phase: 'Solid', discovered: 'Ancient', position: { period: 5, group: 14 } },
    { atomicNumber: 51, symbol: 'Sb', name: 'Antimony', atomicMass: 121.76, category: 'metalloids', electronConfig: '[Kr] 4d¹⁰ 5s² 5p³', phase: 'Solid', discovered: 'Ancient', position: { period: 5, group: 15 } },
    { atomicNumber: 52, symbol: 'Te', name: 'Tellurium', atomicMass: 127.60, category: 'metalloids', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴', phase: 'Solid', discovered: 1782, position: { period: 5, group: 16 } },
    { atomicNumber: 53, symbol: 'I', name: 'Iodine', atomicMass: 126.90, category: 'halogens', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵', phase: 'Solid', discovered: 1811, position: { period: 5, group: 17 } },
    { atomicNumber: 54, symbol: 'Xe', name: 'Xenon', atomicMass: 131.29, category: 'noble-gases', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶', phase: 'Gas', discovered: 1898, position: { period: 5, group: 18 } },
    
    // Period 6
    { atomicNumber: 55, symbol: 'Cs', name: 'Cesium', atomicMass: 132.91, category: 'alkali-metals', electronConfig: '[Xe] 6s¹', phase: 'Solid', discovered: 1860, position: { period: 6, group: 1 } },
    { atomicNumber: 56, symbol: 'Ba', name: 'Barium', atomicMass: 137.33, category: 'alkaline-earth-metals', electronConfig: '[Xe] 6s²', phase: 'Solid', discovered: 1808, position: { period: 6, group: 2 } },
    { atomicNumber: 57, symbol: 'La', name: 'Lanthanum', atomicMass: 138.91, category: 'lanthanides', electronConfig: '[Xe] 5d¹ 6s²', phase: 'Solid', discovered: 1839, position: { period: 6, group: 3 } },
    { atomicNumber: 58, symbol: 'Ce', name: 'Cerium', atomicMass: 140.12, category: 'lanthanides', electronConfig: '[Xe] 4f¹ 5d¹ 6s²', phase: 'Solid', discovered: 1803, position: { period: 8, group: 4 } },
    { atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium', atomicMass: 140.91, category: 'lanthanides', electronConfig: '[Xe] 4f³ 6s²', phase: 'Solid', discovered: 1885, position: { period: 8, group: 5 } },
    { atomicNumber: 60, symbol: 'Nd', name: 'Neodymium', atomicMass: 144.24, category: 'lanthanides', electronConfig: '[Xe] 4f⁴ 6s²', phase: 'Solid', discovered: 1885, position: { period: 8, group: 6 } },
    { atomicNumber: 61, symbol: 'Pm', name: 'Promethium', atomicMass: 145, category: 'lanthanides', electronConfig: '[Xe] 4f⁵ 6s²', phase: 'Solid', discovered: 1945, position: { period: 8, group: 7 } },
    { atomicNumber: 62, symbol: 'Sm', name: 'Samarium', atomicMass: 150.36, category: 'lanthanides', electronConfig: '[Xe] 4f⁶ 6s²', phase: 'Solid', discovered: 1879, position: { period: 8, group: 8 } },
    { atomicNumber: 63, symbol: 'Eu', name: 'Europium', atomicMass: 151.96, category: 'lanthanides', electronConfig: '[Xe] 4f⁷ 6s²', phase: 'Solid', discovered: 1901, position: { period: 8, group: 9 } },
    { atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium', atomicMass: 157.25, category: 'lanthanides', electronConfig: '[Xe] 4f⁷ 5d¹ 6s²', phase: 'Solid', discovered: 1880, position: { period: 8, group: 10 } },
    { atomicNumber: 65, symbol: 'Tb', name: 'Terbium', atomicMass: 158.93, category: 'lanthanides', electronConfig: '[Xe] 4f⁹ 6s²', phase: 'Solid', discovered: 1843, position: { period: 8, group: 11 } },
    { atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium', atomicMass: 162.50, category: 'lanthanides', electronConfig: '[Xe] 4f¹⁰ 6s²', phase: 'Solid', discovered: 1886, position: { period: 8, group: 12 } },
    { atomicNumber: 67, symbol: 'Ho', name: 'Holmium', atomicMass: 164.93, category: 'lanthanides', electronConfig: '[Xe] 4f¹¹ 6s²', phase: 'Solid', discovered: 1867, position: { period: 8, group: 13 } },
    { atomicNumber: 68, symbol: 'Er', name: 'Erbium', atomicMass: 167.26, category: 'lanthanides', electronConfig: '[Xe] 4f¹² 6s²', phase: 'Solid', discovered: 1843, position: { period: 8, group: 14 } },
    { atomicNumber: 69, symbol: 'Tm', name: 'Thulium', atomicMass: 168.93, category: 'lanthanides', electronConfig: '[Xe] 4f¹³ 6s²', phase: 'Solid', discovered: 1879, position: { period: 8, group: 15 } },
    { atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium', atomicMass: 173.05, category: 'lanthanides', electronConfig: '[Xe] 4f¹⁴ 6s²', phase: 'Solid', discovered: 1878, position: { period: 8, group: 16 } },
    { atomicNumber: 71, symbol: 'Lu', name: 'Lutetium', atomicMass: 174.97, category: 'lanthanides', electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²', phase: 'Solid', discovered: 1907, position: { period: 8, group: 17 } },
    { atomicNumber: 72, symbol: 'Hf', name: 'Hafnium', atomicMass: 178.49, category: 'transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d² 6s²', phase: 'Solid', discovered: 1923, position: { period: 6, group: 4 } },
    { atomicNumber: 73, symbol: 'Ta', name: 'Tantalum', atomicMass: 180.95, category: 'transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²', phase: 'Solid', discovered: 1802, position: { period: 6, group: 5 } },
    { atomicNumber: 74, symbol: 'W', name: 'Tungsten', atomicMass: 183.84, category: 'transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²', phase: 'Solid', discovered: 1783, position: { period: 6, group: 6 } },
    { atomicNumber: 75, symbol: 'Re', name: 'Rhenium', atomicMass: 186.21, category: 'transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²', phase: 'Solid', discovered: 1925, position: { period: 6, group: 7 } },
    { atomicNumber: 76, symbol: 'Os', name: 'Osmium', atomicMass: 190.23, category: 'transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²', phase: 'Solid', discovered: 1803, position: { period: 6, group: 8 } },
    { atomicNumber: 77, symbol: 'Ir', name: 'Iridium', atomicMass: 192.22, category: 'transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²', phase: 'Solid', discovered: 1803, position: { period: 6, group: 9 } },
    { atomicNumber: 78, symbol: 'Pt', name: 'Platinum', atomicMass: 195.08, category: 'transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹', phase: 'Solid', discovered: 1735, position: { period: 6, group: 10 } },
    { atomicNumber: 79, symbol: 'Au', name: 'Gold', atomicMass: 196.97, category: 'transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', phase: 'Solid', discovered: 'Ancient', position: { period: 6, group: 11 } },
    { atomicNumber: 80, symbol: 'Hg', name: 'Mercury', atomicMass: 200.59, category: 'transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²', phase: 'Liquid', discovered: 'Ancient', position: { period: 6, group: 12 } },
    { atomicNumber: 81, symbol: 'Tl', name: 'Thallium', atomicMass: 204.38, category: 'post-transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', phase: 'Solid', discovered: 1861, position: { period: 6, group: 13 } },
    { atomicNumber: 82, symbol: 'Pb', name: 'Lead', atomicMass: 207.2, category: 'post-transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', phase: 'Solid', discovered: 'Ancient', position: { period: 6, group: 14 } },
    { atomicNumber: 83, symbol: 'Bi', name: 'Bismuth', atomicMass: 208.98, category: 'post-transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', phase: 'Solid', discovered: 1753, position: { period: 6, group: 15 } },
    { atomicNumber: 84, symbol: 'Po', name: 'Polonium', atomicMass: 209, category: 'post-transition-metals', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', phase: 'Solid', discovered: 1898, position: { period: 6, group: 16 } },
    { atomicNumber: 85, symbol: 'At', name: 'Astatine', atomicMass: 210, category: 'halogens', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', phase: 'Solid', discovered: 1940, position: { period: 6, group: 17 } },
    { atomicNumber: 86, symbol: 'Rn', name: 'Radon', atomicMass: 222, category: 'noble-gases', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', phase: 'Gas', discovered: 1900, position: { period: 6, group: 18 } },
    
    // Period 7
    { atomicNumber: 87, symbol: 'Fr', name: 'Francium', atomicMass: 223, category: 'alkali-metals', electronConfig: '[Rn] 7s¹', phase: 'Solid', discovered: 1939, position: { period: 7, group: 1 } },
    { atomicNumber: 88, symbol: 'Ra', name: 'Radium', atomicMass: 226, category: 'alkaline-earth-metals', electronConfig: '[Rn] 7s²', phase: 'Solid', discovered: 1898, position: { period: 7, group: 2 } },
    { atomicNumber: 89, symbol: 'Ac', name: 'Actinium', atomicMass: 227, category: 'actinides', electronConfig: '[Rn] 6d¹ 7s²', phase: 'Solid', discovered: 1899, position: { period: 7, group: 3 } },
    { atomicNumber: 90, symbol: 'Th', name: 'Thorium', atomicMass: 232.04, category: 'actinides', electronConfig: '[Rn] 6d² 7s²', phase: 'Solid', discovered: 1828, position: { period: 9, group: 4 } },
    { atomicNumber: 91, symbol: 'Pa', name: 'Protactinium', atomicMass: 231.04, category: 'actinides', electronConfig: '[Rn] 5f² 6d¹ 7s²', phase: 'Solid', discovered: 1913, position: { period: 9, group: 5 } },
    { atomicNumber: 92, symbol: 'U', name: 'Uranium', atomicMass: 238.03, category: 'actinides', electronConfig: '[Rn] 5f³ 6d¹ 7s²', phase: 'Solid', discovered: 1789, position: { period: 9, group: 6 } },
    { atomicNumber: 93, symbol: 'Np', name: 'Neptunium', atomicMass: 237, category: 'actinides', electronConfig: '[Rn] 5f⁴ 6d¹ 7s²', phase: 'Solid', discovered: 1940, position: { period: 9, group: 7 } },
    { atomicNumber: 94, symbol: 'Pu', name: 'Plutonium', atomicMass: 244, category: 'actinides', electronConfig: '[Rn] 5f⁶ 7s²', phase: 'Solid', discovered: 1940, position: { period: 9, group: 8 } },
    { atomicNumber: 95, symbol: 'Am', name: 'Americium', atomicMass: 243, category: 'actinides', electronConfig: '[Rn] 5f⁷ 7s²', phase: 'Solid', discovered: 1944, position: { period: 9, group: 9 } },
    { atomicNumber: 96, symbol: 'Cm', name: 'Curium', atomicMass: 247, category: 'actinides', electronConfig: '[Rn] 5f⁷ 6d¹ 7s²', phase: 'Solid', discovered: 1944, position: { period: 9, group: 10 } },
    { atomicNumber: 97, symbol: 'Bk', name: 'Berkelium', atomicMass: 247, category: 'actinides', electronConfig: '[Rn] 5f⁹ 7s²', phase: 'Solid', discovered: 1949, position: { period: 9, group: 11 } },
    { atomicNumber: 98, symbol: 'Cf', name: 'Californium', atomicMass: 251, category: 'actinides', electronConfig: '[Rn] 5f¹⁰ 7s²', phase: 'Solid', discovered: 1950, position: { period: 9, group: 12 } },
    { atomicNumber: 99, symbol: 'Es', name: 'Einsteinium', atomicMass: 252, category: 'actinides', electronConfig: '[Rn] 5f¹¹ 7s²', phase: 'Solid', discovered: 1952, position: { period: 9, group: 13 } },
    { atomicNumber: 100, symbol: 'Fm', name: 'Fermium', atomicMass: 257, category: 'actinides', electronConfig: '[Rn] 5f¹² 7s²', phase: 'Solid', discovered: 1952, position: { period: 9, group: 14 } },
    { atomicNumber: 101, symbol: 'Md', name: 'Mendelevium', atomicMass: 258, category: 'actinides', electronConfig: '[Rn] 5f¹³ 7s²', phase: 'Solid', discovered: 1955, position: { period: 9, group: 15 } },
    { atomicNumber: 102, symbol: 'No', name: 'Nobelium', atomicMass: 259, category: 'actinides', electronConfig: '[Rn] 5f¹⁴ 7s²', phase: 'Solid', discovered: 1966, position: { period: 9, group: 16 } },
    { atomicNumber: 103, symbol: 'Lr', name: 'Lawrencium', atomicMass: 266, category: 'actinides', electronConfig: '[Rn] 5f¹⁴ 6d¹ 7s²', phase: 'Solid', discovered: 1961, position: { period: 9, group: 17 } },
    { atomicNumber: 104, symbol: 'Rf', name: 'Rutherfordium', atomicMass: 267, category: 'transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d² 7s²', phase: 'Solid', discovered: 1969, position: { period: 7, group: 4 } },
    { atomicNumber: 105, symbol: 'Db', name: 'Dubnium', atomicMass: 268, category: 'transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²', phase: 'Solid', discovered: 1970, position: { period: 7, group: 5 } },
    { atomicNumber: 106, symbol: 'Sg', name: 'Seaborgium', atomicMass: 269, category: 'transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²', phase: 'Solid', discovered: 1974, position: { period: 7, group: 6 } },
    { atomicNumber: 107, symbol: 'Bh', name: 'Bohrium', atomicMass: 270, category: 'transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²', phase: 'Solid', discovered: 1981, position: { period: 7, group: 7 } },
    { atomicNumber: 108, symbol: 'Hs', name: 'Hassium', atomicMass: 277, category: 'transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²', phase: 'Solid', discovered: 1984, position: { period: 7, group: 8 } },
    { atomicNumber: 109, symbol: 'Mt', name: 'Meitnerium', atomicMass: 278, category: 'transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²', phase: 'Solid', discovered: 1982, position: { period: 7, group: 9 } },
    { atomicNumber: 110, symbol: 'Ds', name: 'Darmstadtium', atomicMass: 281, category: 'transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d⁸ 7s²', phase: 'Solid', discovered: 1994, position: { period: 7, group: 10 } },
    { atomicNumber: 111, symbol: 'Rg', name: 'Roentgenium', atomicMass: 282, category: 'transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s²', phase: 'Solid', discovered: 1994, position: { period: 7, group: 11 } },
    { atomicNumber: 112, symbol: 'Cn', name: 'Copernicium', atomicMass: 285, category: 'transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', phase: 'Solid', discovered: 1996, position: { period: 7, group: 12 } },
    { atomicNumber: 113, symbol: 'Nh', name: 'Nihonium', atomicMass: 286, category: 'post-transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', phase: 'Solid', discovered: 2004, position: { period: 7, group: 13 } },
    { atomicNumber: 114, symbol: 'Fl', name: 'Flerovium', atomicMass: 289, category: 'post-transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', phase: 'Solid', discovered: 1999, position: { period: 7, group: 14 } },
    { atomicNumber: 115, symbol: 'Mc', name: 'Moscovium', atomicMass: 290, category: 'post-transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', phase: 'Solid', discovered: 2003, position: { period: 7, group: 15 } },
    { atomicNumber: 116, symbol: 'Lv', name: 'Livermorium', atomicMass: 293, category: 'post-transition-metals', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', phase: 'Solid', discovered: 2000, position: { period: 7, group: 16 } },
    { atomicNumber: 117, symbol: 'Ts', name: 'Tennessine', atomicMass: 294, category: 'halogens', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', phase: 'Solid', discovered: 2010, position: { period: 7, group: 17 } },
    { atomicNumber: 118, symbol: 'Og', name: 'Oganesson', atomicMass: 294, category: 'noble-gases', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', phase: 'Solid', discovered: 2002, position: { period: 7, group: 18 } }
];

// Category display names for better UX
const categoryNames = {
    'alkali-metals': 'Alkali Metal',
    'alkaline-earth-metals': 'Alkaline Earth Metal',
    'transition-metals': 'Transition Metal',
    'post-transition-metals': 'Post-transition Metal',
    'metalloids': 'Metalloid',
    'nonmetals': 'Nonmetal',
    'halogens': 'Halogen',
    'noble-gases': 'Noble Gas',
    'lanthanides': 'Lanthanide',
    'actinides': 'Actinide'
};